services:
  postgres:
    image: postgres:16-alpine
    container_name: kozmocart_postgres
    environment:
      POSTGRES_USER: kozmocart
      POSTGRES_PASSWORD: kozmocart_dev_2026
      POSTGRES_DB: kozmocart_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kozmocart -d kozmocart_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: kozmocart_redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  api:
    build: ./backend
    container_name: kozmocart_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql+asyncpg://kozmocart:kozmocart_dev_2026@postgres:5432/kozmocart_db
      REDIS_URL: redis://redis:6379/0
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: info@kozmocart.com
      SMTP_PASSWORD: "boxr xytu ycye snof"
      SMTP_FROM_EMAIL: info@kozmocart.com
      SMTP_FROM_NAME: "Kozmocart.com"
      SMTP_TLS: "true"
      SMTP_SSL: "false"
    ports:
      - "8020:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  admin:
    build: ./frontend
    container_name: kozmocart_admin
    environment:
      VITE_API_BASE_URL: /api/v1
      VITE_STATIC_BASE_URL: ""
    ports:
      - "5173:5173"
    depends_on:
      - api

  storefront:
    build: ./storefront
    container_name: kozmocart_storefront
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
