"""Add SEO and GEO fields

Revision ID: 453879f1fd4c
Revises: 
Create Date: 2026-05-11 20:39:39.113278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '453879f1fd4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('seo_title', sa.String(length=70), nullable=True))
    op.add_column('brands', sa.Column('meta_description', sa.String(length=165), nullable=True))
    op.add_column('brands', sa.Column('keywords', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('seo_title', sa.String(length=70), nullable=True))
    op.add_column('categories', sa.Column('meta_description', sa.String(length=165), nullable=True))
    op.add_column('categories', sa.Column('keywords', sa.Text(), nullable=True))
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('products', sa.Column('shipping_zones_excluded', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'shipping_zones_excluded')
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('categories', 'keywords')
    op.drop_column('categories', 'meta_description')
    op.drop_column('categories', 'seo_title')
    op.drop_column('brands', 'keywords')
    op.drop_column('brands', 'meta_description')
    op.drop_column('brands', 'seo_title')
    # ### end Alembic commands ###
