"""add_new_arrival_and_priority_to_products

Revision ID: aba13e5cfc27
Revises: f894001afaad
Create Date: 2026-06-18 11:10:48.186183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_new_arrival_and_priority_to_products

Revision ID: aba13e5cfc27
Revises: f894001afaad
Create Date: 2026-06-18 11:10:48.186183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aba13e5cfc27'
down_revision: Union[str, None] = 'f894001afaad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('brands')]
    
    if 'is_3d_active' in columns:
        op.alter_column('brands', 'is_3d_active',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('false'))
    if 'remove_background' in columns:
        op.alter_column('brands', 'remove_background',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('true'))
    if 'exclusivity_toggle' in columns:
        op.alter_column('brands', 'exclusivity_toggle',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('false'))
    if 'images' in columns:
        op.drop_column('brands', 'images')
        
    op.add_column('products', sa.Column('is_new_arrival', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('products', sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('brands')]
    
    op.drop_column('products', 'priority')
    op.drop_column('products', 'is_new_arrival')
    
    if 'images' not in columns:
        op.add_column('brands', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    if 'exclusivity_toggle' in columns:
        op.alter_column('brands', 'exclusivity_toggle',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))
    if 'remove_background' in columns:
        op.alter_column('brands', 'remove_background',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('true'))
    if 'is_3d_active' in columns:
        op.alter_column('brands', 'is_3d_active',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
