"""enhance_order_model

Revision ID: df796d214506
Revises: 453879f1fd4c
Create Date: 2026-05-11 21:26:58.622134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df796d214506'
down_revision: Union[str, None] = '453879f1fd4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('transaction_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('payment_gateway', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('payment_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_details')
    op.drop_column('orders', 'payment_gateway')
    op.drop_column('orders', 'transaction_id')
    op.drop_column('orders', 'billing_address')
    op.drop_column('orders', 'customer_email')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
